
word = input('Enter a word: ')
i = word.upper()
print(i)
print(f'***********\n',end="")
print(f'**={i}=**\n',end="")
print(f'**={i}=**\n',end="")
print(f'**={i}=**\n',end="")
print(f'**={i}=**\n',end="")
print(f'**={i}=**\n',end="")
print(f'***********',end ="")
